spring.application.name=document-service-java

aws.access-key=AWS_ACCESS_KEY_ID
aws.secret-key=AWS_SECRET_ACCESS_KEY
aws.s3.region=AWS_REGION
aws.dynamodb.region=AWS_REGION
server.port=8003


aws.s3.bucket=ferreteria-documents-dev
aws.dynamodb.table=DocumentsMetadata

